/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WaitlistRouteImport } from './routes/waitlist'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LgpdRouteImport } from './routes/lgpd'
import { Route as EsqueciSenhaRouteImport } from './routes/esqueci-senha'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppCasosIndexRouteImport } from './routes/app.casos.index'
import { Route as AppCasosNovoRouteImport } from './routes/app.casos.novo'
import { Route as AppCasosIdRouteImport } from './routes/app.casos.$id'
import { Route as ApiIaGenerateDeliverableRouteImport } from './routes/api.ia.generate-deliverable'
import { Route as ApiIaExtractDocumentRouteImport } from './routes/api.ia.extract-document'
import { Route as ApiIaEstimateJurimetricsRouteImport } from './routes/api.ia.estimate-jurimetrics'
import { Route as ApiIaClassifyDenialRouteImport } from './routes/api.ia.classify-denial'

const WaitlistRoute = WaitlistRouteImport.update({
  id: '/waitlist',
  path: '/waitlist',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LgpdRoute = LgpdRouteImport.update({
  id: '/lgpd',
  path: '/lgpd',
  getParentRoute: () => rootRouteImport,
} as any)
const EsqueciSenhaRoute = EsqueciSenhaRouteImport.update({
  id: '/esqueci-senha',
  path: '/esqueci-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppCasosIndexRoute = AppCasosIndexRouteImport.update({
  id: '/casos/',
  path: '/casos/',
  getParentRoute: () => AppRoute,
} as any)
const AppCasosNovoRoute = AppCasosNovoRouteImport.update({
  id: '/casos/novo',
  path: '/casos/novo',
  getParentRoute: () => AppRoute,
} as any)
const AppCasosIdRoute = AppCasosIdRouteImport.update({
  id: '/casos/$id',
  path: '/casos/$id',
  getParentRoute: () => AppRoute,
} as any)
const ApiIaGenerateDeliverableRoute =
  ApiIaGenerateDeliverableRouteImport.update({
    id: '/api/ia/generate-deliverable',
    path: '/api/ia/generate-deliverable',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIaExtractDocumentRoute = ApiIaExtractDocumentRouteImport.update({
  id: '/api/ia/extract-document',
  path: '/api/ia/extract-document',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIaEstimateJurimetricsRoute =
  ApiIaEstimateJurimetricsRouteImport.update({
    id: '/api/ia/estimate-jurimetrics',
    path: '/api/ia/estimate-jurimetrics',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIaClassifyDenialRoute = ApiIaClassifyDenialRouteImport.update({
  id: '/api/ia/classify-denial',
  path: '/api/ia/classify-denial',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/demo': typeof DemoRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/lgpd': typeof LgpdRoute
  '/login': typeof LoginRoute
  '/privacidade': typeof PrivacidadeRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/termos': typeof TermosRoute
  '/waitlist': typeof WaitlistRoute
  '/app/': typeof AppIndexRoute
  '/api/ia/classify-denial': typeof ApiIaClassifyDenialRoute
  '/api/ia/estimate-jurimetrics': typeof ApiIaEstimateJurimetricsRoute
  '/api/ia/extract-document': typeof ApiIaExtractDocumentRoute
  '/api/ia/generate-deliverable': typeof ApiIaGenerateDeliverableRoute
  '/app/casos/$id': typeof AppCasosIdRoute
  '/app/casos/novo': typeof AppCasosNovoRoute
  '/app/casos/': typeof AppCasosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/lgpd': typeof LgpdRoute
  '/login': typeof LoginRoute
  '/privacidade': typeof PrivacidadeRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/termos': typeof TermosRoute
  '/waitlist': typeof WaitlistRoute
  '/app': typeof AppIndexRoute
  '/api/ia/classify-denial': typeof ApiIaClassifyDenialRoute
  '/api/ia/estimate-jurimetrics': typeof ApiIaEstimateJurimetricsRoute
  '/api/ia/extract-document': typeof ApiIaExtractDocumentRoute
  '/api/ia/generate-deliverable': typeof ApiIaGenerateDeliverableRoute
  '/app/casos/$id': typeof AppCasosIdRoute
  '/app/casos/novo': typeof AppCasosNovoRoute
  '/app/casos': typeof AppCasosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/demo': typeof DemoRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/lgpd': typeof LgpdRoute
  '/login': typeof LoginRoute
  '/privacidade': typeof PrivacidadeRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/termos': typeof TermosRoute
  '/waitlist': typeof WaitlistRoute
  '/app/': typeof AppIndexRoute
  '/api/ia/classify-denial': typeof ApiIaClassifyDenialRoute
  '/api/ia/estimate-jurimetrics': typeof ApiIaEstimateJurimetricsRoute
  '/api/ia/extract-document': typeof ApiIaExtractDocumentRoute
  '/api/ia/generate-deliverable': typeof ApiIaGenerateDeliverableRoute
  '/app/casos/$id': typeof AppCasosIdRoute
  '/app/casos/novo': typeof AppCasosNovoRoute
  '/app/casos/': typeof AppCasosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/demo'
    | '/esqueci-senha'
    | '/lgpd'
    | '/login'
    | '/privacidade'
    | '/redefinir-senha'
    | '/termos'
    | '/waitlist'
    | '/app/'
    | '/api/ia/classify-denial'
    | '/api/ia/estimate-jurimetrics'
    | '/api/ia/extract-document'
    | '/api/ia/generate-deliverable'
    | '/app/casos/$id'
    | '/app/casos/novo'
    | '/app/casos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo'
    | '/esqueci-senha'
    | '/lgpd'
    | '/login'
    | '/privacidade'
    | '/redefinir-senha'
    | '/termos'
    | '/waitlist'
    | '/app'
    | '/api/ia/classify-denial'
    | '/api/ia/estimate-jurimetrics'
    | '/api/ia/extract-document'
    | '/api/ia/generate-deliverable'
    | '/app/casos/$id'
    | '/app/casos/novo'
    | '/app/casos'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/demo'
    | '/esqueci-senha'
    | '/lgpd'
    | '/login'
    | '/privacidade'
    | '/redefinir-senha'
    | '/termos'
    | '/waitlist'
    | '/app/'
    | '/api/ia/classify-denial'
    | '/api/ia/estimate-jurimetrics'
    | '/api/ia/extract-document'
    | '/api/ia/generate-deliverable'
    | '/app/casos/$id'
    | '/app/casos/novo'
    | '/app/casos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  DemoRoute: typeof DemoRoute
  EsqueciSenhaRoute: typeof EsqueciSenhaRoute
  LgpdRoute: typeof LgpdRoute
  LoginRoute: typeof LoginRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  TermosRoute: typeof TermosRoute
  WaitlistRoute: typeof WaitlistRoute
  ApiIaClassifyDenialRoute: typeof ApiIaClassifyDenialRoute
  ApiIaEstimateJurimetricsRoute: typeof ApiIaEstimateJurimetricsRoute
  ApiIaExtractDocumentRoute: typeof ApiIaExtractDocumentRoute
  ApiIaGenerateDeliverableRoute: typeof ApiIaGenerateDeliverableRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/waitlist': {
      id: '/waitlist'
      path: '/waitlist'
      fullPath: '/waitlist'
      preLoaderRoute: typeof WaitlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lgpd': {
      id: '/lgpd'
      path: '/lgpd'
      fullPath: '/lgpd'
      preLoaderRoute: typeof LgpdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esqueci-senha': {
      id: '/esqueci-senha'
      path: '/esqueci-senha'
      fullPath: '/esqueci-senha'
      preLoaderRoute: typeof EsqueciSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/casos/': {
      id: '/app/casos/'
      path: '/casos'
      fullPath: '/app/casos/'
      preLoaderRoute: typeof AppCasosIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/casos/novo': {
      id: '/app/casos/novo'
      path: '/casos/novo'
      fullPath: '/app/casos/novo'
      preLoaderRoute: typeof AppCasosNovoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/casos/$id': {
      id: '/app/casos/$id'
      path: '/casos/$id'
      fullPath: '/app/casos/$id'
      preLoaderRoute: typeof AppCasosIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/ia/generate-deliverable': {
      id: '/api/ia/generate-deliverable'
      path: '/api/ia/generate-deliverable'
      fullPath: '/api/ia/generate-deliverable'
      preLoaderRoute: typeof ApiIaGenerateDeliverableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ia/extract-document': {
      id: '/api/ia/extract-document'
      path: '/api/ia/extract-document'
      fullPath: '/api/ia/extract-document'
      preLoaderRoute: typeof ApiIaExtractDocumentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ia/estimate-jurimetrics': {
      id: '/api/ia/estimate-jurimetrics'
      path: '/api/ia/estimate-jurimetrics'
      fullPath: '/api/ia/estimate-jurimetrics'
      preLoaderRoute: typeof ApiIaEstimateJurimetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ia/classify-denial': {
      id: '/api/ia/classify-denial'
      path: '/api/ia/classify-denial'
      fullPath: '/api/ia/classify-denial'
      preLoaderRoute: typeof ApiIaClassifyDenialRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppCasosIdRoute: typeof AppCasosIdRoute
  AppCasosNovoRoute: typeof AppCasosNovoRoute
  AppCasosIndexRoute: typeof AppCasosIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppCasosIdRoute: AppCasosIdRoute,
  AppCasosNovoRoute: AppCasosNovoRoute,
  AppCasosIndexRoute: AppCasosIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  DemoRoute: DemoRoute,
  EsqueciSenhaRoute: EsqueciSenhaRoute,
  LgpdRoute: LgpdRoute,
  LoginRoute: LoginRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  TermosRoute: TermosRoute,
  WaitlistRoute: WaitlistRoute,
  ApiIaClassifyDenialRoute: ApiIaClassifyDenialRoute,
  ApiIaEstimateJurimetricsRoute: ApiIaEstimateJurimetricsRoute,
  ApiIaExtractDocumentRoute: ApiIaExtractDocumentRoute,
  ApiIaGenerateDeliverableRoute: ApiIaGenerateDeliverableRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
