/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WaitlistRouteImport } from './routes/waitlist'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as MinhaContaRouteImport } from './routes/minha-conta'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LgpdRouteImport } from './routes/lgpd'
import { Route as EsqueciSenhaRouteImport } from './routes/esqueci-senha'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as ConfirmarEmailRouteImport } from './routes/confirmar-email'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppCasosIndexRouteImport } from './routes/app.casos.index'
import { Route as AppCasosNovoRouteImport } from './routes/app.casos.novo'
import { Route as AppCasosIdRouteImport } from './routes/app.casos.$id'
import { Route as ApiIaGenerateDeliverableRouteImport } from './routes/api.ia.generate-deliverable'
import { Route as ApiIaExtractDocumentRouteImport } from './routes/api.ia.extract-document'
import { Route as ApiIaEstimateJurimetricsRouteImport } from './routes/api.ia.estimate-jurimetrics'
import { Route as ApiIaClassifyDenialRouteImport } from './routes/api.ia.classify-denial'
import { Route as ApiPublicHooksExpurgarArtifactsRouteImport } from './routes/api.public.hooks.expurgar-artifacts'
import { Route as ApiIaSaudejusiaGenerateRouteImport } from './routes/api.ia.saudejusia.generate'
import { Route as ApiIaSaudejusiaExtractRouteImport } from './routes/api.ia.saudejusia.extract'
import { Route as ApiIaSaudejusiaClassifyRouteImport } from './routes/api.ia.saudejusia.classify'
import { Route as ApiIaSaudejusiaAnalyzeRouteImport } from './routes/api.ia.saudejusia.analyze'
import { Route as ApiIaSaudejusiaArtifactIdRouteImport } from './routes/api.ia.saudejusia.artifact.$id'

const WaitlistRoute = WaitlistRouteImport.update({
  id: '/waitlist',
  path: '/waitlist',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhaContaRoute = MinhaContaRouteImport.update({
  id: '/minha-conta',
  path: '/minha-conta',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LgpdRoute = LgpdRouteImport.update({
  id: '/lgpd',
  path: '/lgpd',
  getParentRoute: () => rootRouteImport,
} as any)
const EsqueciSenhaRoute = EsqueciSenhaRouteImport.update({
  id: '/esqueci-senha',
  path: '/esqueci-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmarEmailRoute = ConfirmarEmailRouteImport.update({
  id: '/confirmar-email',
  path: '/confirmar-email',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppCasosIndexRoute = AppCasosIndexRouteImport.update({
  id: '/casos/',
  path: '/casos/',
  getParentRoute: () => AppRoute,
} as any)
const AppCasosNovoRoute = AppCasosNovoRouteImport.update({
  id: '/casos/novo',
  path: '/casos/novo',
  getParentRoute: () => AppRoute,
} as any)
const AppCasosIdRoute = AppCasosIdRouteImport.update({
  id: '/casos/$id',
  path: '/casos/$id',
  getParentRoute: () => AppRoute,
} as any)
const ApiIaGenerateDeliverableRoute =
  ApiIaGenerateDeliverableRouteImport.update({
    id: '/api/ia/generate-deliverable',
    path: '/api/ia/generate-deliverable',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIaExtractDocumentRoute = ApiIaExtractDocumentRouteImport.update({
  id: '/api/ia/extract-document',
  path: '/api/ia/extract-document',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIaEstimateJurimetricsRoute =
  ApiIaEstimateJurimetricsRouteImport.update({
    id: '/api/ia/estimate-jurimetrics',
    path: '/api/ia/estimate-jurimetrics',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIaClassifyDenialRoute = ApiIaClassifyDenialRouteImport.update({
  id: '/api/ia/classify-denial',
  path: '/api/ia/classify-denial',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksExpurgarArtifactsRoute =
  ApiPublicHooksExpurgarArtifactsRouteImport.update({
    id: '/api/public/hooks/expurgar-artifacts',
    path: '/api/public/hooks/expurgar-artifacts',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIaSaudejusiaGenerateRoute = ApiIaSaudejusiaGenerateRouteImport.update({
  id: '/api/ia/saudejusia/generate',
  path: '/api/ia/saudejusia/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIaSaudejusiaExtractRoute = ApiIaSaudejusiaExtractRouteImport.update({
  id: '/api/ia/saudejusia/extract',
  path: '/api/ia/saudejusia/extract',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIaSaudejusiaClassifyRoute = ApiIaSaudejusiaClassifyRouteImport.update({
  id: '/api/ia/saudejusia/classify',
  path: '/api/ia/saudejusia/classify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIaSaudejusiaAnalyzeRoute = ApiIaSaudejusiaAnalyzeRouteImport.update({
  id: '/api/ia/saudejusia/analyze',
  path: '/api/ia/saudejusia/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIaSaudejusiaArtifactIdRoute =
  ApiIaSaudejusiaArtifactIdRouteImport.update({
    id: '/api/ia/saudejusia/artifact/$id',
    path: '/api/ia/saudejusia/artifact/$id',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/confirmar-email': typeof ConfirmarEmailRoute
  '/demo': typeof DemoRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/lgpd': typeof LgpdRoute
  '/login': typeof LoginRoute
  '/minha-conta': typeof MinhaContaRoute
  '/privacidade': typeof PrivacidadeRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/signup': typeof SignupRoute
  '/termos': typeof TermosRoute
  '/waitlist': typeof WaitlistRoute
  '/app/': typeof AppIndexRoute
  '/api/ia/classify-denial': typeof ApiIaClassifyDenialRoute
  '/api/ia/estimate-jurimetrics': typeof ApiIaEstimateJurimetricsRoute
  '/api/ia/extract-document': typeof ApiIaExtractDocumentRoute
  '/api/ia/generate-deliverable': typeof ApiIaGenerateDeliverableRoute
  '/app/casos/$id': typeof AppCasosIdRoute
  '/app/casos/novo': typeof AppCasosNovoRoute
  '/app/casos/': typeof AppCasosIndexRoute
  '/api/ia/saudejusia/analyze': typeof ApiIaSaudejusiaAnalyzeRoute
  '/api/ia/saudejusia/classify': typeof ApiIaSaudejusiaClassifyRoute
  '/api/ia/saudejusia/extract': typeof ApiIaSaudejusiaExtractRoute
  '/api/ia/saudejusia/generate': typeof ApiIaSaudejusiaGenerateRoute
  '/api/public/hooks/expurgar-artifacts': typeof ApiPublicHooksExpurgarArtifactsRoute
  '/api/ia/saudejusia/artifact/$id': typeof ApiIaSaudejusiaArtifactIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/confirmar-email': typeof ConfirmarEmailRoute
  '/demo': typeof DemoRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/lgpd': typeof LgpdRoute
  '/login': typeof LoginRoute
  '/minha-conta': typeof MinhaContaRoute
  '/privacidade': typeof PrivacidadeRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/signup': typeof SignupRoute
  '/termos': typeof TermosRoute
  '/waitlist': typeof WaitlistRoute
  '/app': typeof AppIndexRoute
  '/api/ia/classify-denial': typeof ApiIaClassifyDenialRoute
  '/api/ia/estimate-jurimetrics': typeof ApiIaEstimateJurimetricsRoute
  '/api/ia/extract-document': typeof ApiIaExtractDocumentRoute
  '/api/ia/generate-deliverable': typeof ApiIaGenerateDeliverableRoute
  '/app/casos/$id': typeof AppCasosIdRoute
  '/app/casos/novo': typeof AppCasosNovoRoute
  '/app/casos': typeof AppCasosIndexRoute
  '/api/ia/saudejusia/analyze': typeof ApiIaSaudejusiaAnalyzeRoute
  '/api/ia/saudejusia/classify': typeof ApiIaSaudejusiaClassifyRoute
  '/api/ia/saudejusia/extract': typeof ApiIaSaudejusiaExtractRoute
  '/api/ia/saudejusia/generate': typeof ApiIaSaudejusiaGenerateRoute
  '/api/public/hooks/expurgar-artifacts': typeof ApiPublicHooksExpurgarArtifactsRoute
  '/api/ia/saudejusia/artifact/$id': typeof ApiIaSaudejusiaArtifactIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/confirmar-email': typeof ConfirmarEmailRoute
  '/demo': typeof DemoRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/lgpd': typeof LgpdRoute
  '/login': typeof LoginRoute
  '/minha-conta': typeof MinhaContaRoute
  '/privacidade': typeof PrivacidadeRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/signup': typeof SignupRoute
  '/termos': typeof TermosRoute
  '/waitlist': typeof WaitlistRoute
  '/app/': typeof AppIndexRoute
  '/api/ia/classify-denial': typeof ApiIaClassifyDenialRoute
  '/api/ia/estimate-jurimetrics': typeof ApiIaEstimateJurimetricsRoute
  '/api/ia/extract-document': typeof ApiIaExtractDocumentRoute
  '/api/ia/generate-deliverable': typeof ApiIaGenerateDeliverableRoute
  '/app/casos/$id': typeof AppCasosIdRoute
  '/app/casos/novo': typeof AppCasosNovoRoute
  '/app/casos/': typeof AppCasosIndexRoute
  '/api/ia/saudejusia/analyze': typeof ApiIaSaudejusiaAnalyzeRoute
  '/api/ia/saudejusia/classify': typeof ApiIaSaudejusiaClassifyRoute
  '/api/ia/saudejusia/extract': typeof ApiIaSaudejusiaExtractRoute
  '/api/ia/saudejusia/generate': typeof ApiIaSaudejusiaGenerateRoute
  '/api/public/hooks/expurgar-artifacts': typeof ApiPublicHooksExpurgarArtifactsRoute
  '/api/ia/saudejusia/artifact/$id': typeof ApiIaSaudejusiaArtifactIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/cadastro'
    | '/confirmar-email'
    | '/demo'
    | '/esqueci-senha'
    | '/lgpd'
    | '/login'
    | '/minha-conta'
    | '/privacidade'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/signup'
    | '/termos'
    | '/waitlist'
    | '/app/'
    | '/api/ia/classify-denial'
    | '/api/ia/estimate-jurimetrics'
    | '/api/ia/extract-document'
    | '/api/ia/generate-deliverable'
    | '/app/casos/$id'
    | '/app/casos/novo'
    | '/app/casos/'
    | '/api/ia/saudejusia/analyze'
    | '/api/ia/saudejusia/classify'
    | '/api/ia/saudejusia/extract'
    | '/api/ia/saudejusia/generate'
    | '/api/public/hooks/expurgar-artifacts'
    | '/api/ia/saudejusia/artifact/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/confirmar-email'
    | '/demo'
    | '/esqueci-senha'
    | '/lgpd'
    | '/login'
    | '/minha-conta'
    | '/privacidade'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/signup'
    | '/termos'
    | '/waitlist'
    | '/app'
    | '/api/ia/classify-denial'
    | '/api/ia/estimate-jurimetrics'
    | '/api/ia/extract-document'
    | '/api/ia/generate-deliverable'
    | '/app/casos/$id'
    | '/app/casos/novo'
    | '/app/casos'
    | '/api/ia/saudejusia/analyze'
    | '/api/ia/saudejusia/classify'
    | '/api/ia/saudejusia/extract'
    | '/api/ia/saudejusia/generate'
    | '/api/public/hooks/expurgar-artifacts'
    | '/api/ia/saudejusia/artifact/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/cadastro'
    | '/confirmar-email'
    | '/demo'
    | '/esqueci-senha'
    | '/lgpd'
    | '/login'
    | '/minha-conta'
    | '/privacidade'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/signup'
    | '/termos'
    | '/waitlist'
    | '/app/'
    | '/api/ia/classify-denial'
    | '/api/ia/estimate-jurimetrics'
    | '/api/ia/extract-document'
    | '/api/ia/generate-deliverable'
    | '/app/casos/$id'
    | '/app/casos/novo'
    | '/app/casos/'
    | '/api/ia/saudejusia/analyze'
    | '/api/ia/saudejusia/classify'
    | '/api/ia/saudejusia/extract'
    | '/api/ia/saudejusia/generate'
    | '/api/public/hooks/expurgar-artifacts'
    | '/api/ia/saudejusia/artifact/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  ConfirmarEmailRoute: typeof ConfirmarEmailRoute
  DemoRoute: typeof DemoRoute
  EsqueciSenhaRoute: typeof EsqueciSenhaRoute
  LgpdRoute: typeof LgpdRoute
  LoginRoute: typeof LoginRoute
  MinhaContaRoute: typeof MinhaContaRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  SignupRoute: typeof SignupRoute
  TermosRoute: typeof TermosRoute
  WaitlistRoute: typeof WaitlistRoute
  ApiIaClassifyDenialRoute: typeof ApiIaClassifyDenialRoute
  ApiIaEstimateJurimetricsRoute: typeof ApiIaEstimateJurimetricsRoute
  ApiIaExtractDocumentRoute: typeof ApiIaExtractDocumentRoute
  ApiIaGenerateDeliverableRoute: typeof ApiIaGenerateDeliverableRoute
  ApiIaSaudejusiaAnalyzeRoute: typeof ApiIaSaudejusiaAnalyzeRoute
  ApiIaSaudejusiaClassifyRoute: typeof ApiIaSaudejusiaClassifyRoute
  ApiIaSaudejusiaExtractRoute: typeof ApiIaSaudejusiaExtractRoute
  ApiIaSaudejusiaGenerateRoute: typeof ApiIaSaudejusiaGenerateRoute
  ApiPublicHooksExpurgarArtifactsRoute: typeof ApiPublicHooksExpurgarArtifactsRoute
  ApiIaSaudejusiaArtifactIdRoute: typeof ApiIaSaudejusiaArtifactIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/waitlist': {
      id: '/waitlist'
      path: '/waitlist'
      fullPath: '/waitlist'
      preLoaderRoute: typeof WaitlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minha-conta': {
      id: '/minha-conta'
      path: '/minha-conta'
      fullPath: '/minha-conta'
      preLoaderRoute: typeof MinhaContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lgpd': {
      id: '/lgpd'
      path: '/lgpd'
      fullPath: '/lgpd'
      preLoaderRoute: typeof LgpdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esqueci-senha': {
      id: '/esqueci-senha'
      path: '/esqueci-senha'
      fullPath: '/esqueci-senha'
      preLoaderRoute: typeof EsqueciSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmar-email': {
      id: '/confirmar-email'
      path: '/confirmar-email'
      fullPath: '/confirmar-email'
      preLoaderRoute: typeof ConfirmarEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/casos/': {
      id: '/app/casos/'
      path: '/casos'
      fullPath: '/app/casos/'
      preLoaderRoute: typeof AppCasosIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/casos/novo': {
      id: '/app/casos/novo'
      path: '/casos/novo'
      fullPath: '/app/casos/novo'
      preLoaderRoute: typeof AppCasosNovoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/casos/$id': {
      id: '/app/casos/$id'
      path: '/casos/$id'
      fullPath: '/app/casos/$id'
      preLoaderRoute: typeof AppCasosIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/ia/generate-deliverable': {
      id: '/api/ia/generate-deliverable'
      path: '/api/ia/generate-deliverable'
      fullPath: '/api/ia/generate-deliverable'
      preLoaderRoute: typeof ApiIaGenerateDeliverableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ia/extract-document': {
      id: '/api/ia/extract-document'
      path: '/api/ia/extract-document'
      fullPath: '/api/ia/extract-document'
      preLoaderRoute: typeof ApiIaExtractDocumentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ia/estimate-jurimetrics': {
      id: '/api/ia/estimate-jurimetrics'
      path: '/api/ia/estimate-jurimetrics'
      fullPath: '/api/ia/estimate-jurimetrics'
      preLoaderRoute: typeof ApiIaEstimateJurimetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ia/classify-denial': {
      id: '/api/ia/classify-denial'
      path: '/api/ia/classify-denial'
      fullPath: '/api/ia/classify-denial'
      preLoaderRoute: typeof ApiIaClassifyDenialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/expurgar-artifacts': {
      id: '/api/public/hooks/expurgar-artifacts'
      path: '/api/public/hooks/expurgar-artifacts'
      fullPath: '/api/public/hooks/expurgar-artifacts'
      preLoaderRoute: typeof ApiPublicHooksExpurgarArtifactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ia/saudejusia/generate': {
      id: '/api/ia/saudejusia/generate'
      path: '/api/ia/saudejusia/generate'
      fullPath: '/api/ia/saudejusia/generate'
      preLoaderRoute: typeof ApiIaSaudejusiaGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ia/saudejusia/extract': {
      id: '/api/ia/saudejusia/extract'
      path: '/api/ia/saudejusia/extract'
      fullPath: '/api/ia/saudejusia/extract'
      preLoaderRoute: typeof ApiIaSaudejusiaExtractRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ia/saudejusia/classify': {
      id: '/api/ia/saudejusia/classify'
      path: '/api/ia/saudejusia/classify'
      fullPath: '/api/ia/saudejusia/classify'
      preLoaderRoute: typeof ApiIaSaudejusiaClassifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ia/saudejusia/analyze': {
      id: '/api/ia/saudejusia/analyze'
      path: '/api/ia/saudejusia/analyze'
      fullPath: '/api/ia/saudejusia/analyze'
      preLoaderRoute: typeof ApiIaSaudejusiaAnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ia/saudejusia/artifact/$id': {
      id: '/api/ia/saudejusia/artifact/$id'
      path: '/api/ia/saudejusia/artifact/$id'
      fullPath: '/api/ia/saudejusia/artifact/$id'
      preLoaderRoute: typeof ApiIaSaudejusiaArtifactIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppCasosIdRoute: typeof AppCasosIdRoute
  AppCasosNovoRoute: typeof AppCasosNovoRoute
  AppCasosIndexRoute: typeof AppCasosIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppCasosIdRoute: AppCasosIdRoute,
  AppCasosNovoRoute: AppCasosNovoRoute,
  AppCasosIndexRoute: AppCasosIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  CadastroRoute: CadastroRoute,
  ConfirmarEmailRoute: ConfirmarEmailRoute,
  DemoRoute: DemoRoute,
  EsqueciSenhaRoute: EsqueciSenhaRoute,
  LgpdRoute: LgpdRoute,
  LoginRoute: LoginRoute,
  MinhaContaRoute: MinhaContaRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  SignupRoute: SignupRoute,
  TermosRoute: TermosRoute,
  WaitlistRoute: WaitlistRoute,
  ApiIaClassifyDenialRoute: ApiIaClassifyDenialRoute,
  ApiIaEstimateJurimetricsRoute: ApiIaEstimateJurimetricsRoute,
  ApiIaExtractDocumentRoute: ApiIaExtractDocumentRoute,
  ApiIaGenerateDeliverableRoute: ApiIaGenerateDeliverableRoute,
  ApiIaSaudejusiaAnalyzeRoute: ApiIaSaudejusiaAnalyzeRoute,
  ApiIaSaudejusiaClassifyRoute: ApiIaSaudejusiaClassifyRoute,
  ApiIaSaudejusiaExtractRoute: ApiIaSaudejusiaExtractRoute,
  ApiIaSaudejusiaGenerateRoute: ApiIaSaudejusiaGenerateRoute,
  ApiPublicHooksExpurgarArtifactsRoute: ApiPublicHooksExpurgarArtifactsRoute,
  ApiIaSaudejusiaArtifactIdRoute: ApiIaSaudejusiaArtifactIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
